import type { IslemAltSecenek, IslemTipi, AksesuarTanimlar } from "./types";

export const ALT_TO_TIP: Record<IslemAltSecenek, IslemTipi> = {
  satin_alim: "GİRİŞ",
  formaneye_iade: "GİRİŞ",
  diger_giris: "GİRİŞ",
  formaneye_verilen: "ÇIKIŞ",
  satis: "ÇIKIŞ",
  fire: "ÇIKIŞ",
  diger_cikis: "ÇIKIŞ",
  tedarikci_iade: "ÇIKIŞ",
  ambalaja_verilen: "ÇIKIŞ",
};

export const ALT_SECENEKLER: { value: IslemAltSecenek; label: string }[] = [
  { value: "satin_alim", label: "Satın Alım" },
  { value: "formaneye_iade", label: "Formaneye İade" },
  { value: "diger_giris", label: "Diğer Giriş" },
  { value: "formaneye_verilen", label: "Formaneye Verilen" },
  { value: "satis", label: "Satış" },
  { value: "fire", label: "Fire" },
  { value: "diger_cikis", label: "Diğer Çıkış" },
  { value: "tedarikci_iade", label: "Tedarikçi İade" },
  { value: "ambalaja_verilen", label: "Ambalaja Verilen" },
];

export const ALT_SECENEK_LABEL: Record<IslemAltSecenek, string> = Object.fromEntries(
  ALT_SECENEKLER.map((s) => [s.value, s.label])
) as Record<IslemAltSecenek, string>;

export const DEFAULT_TANIMLAR: AksesuarTanimlar = {
  tedarikciler: [
    { id: "t1", name: "Akpamuk" },
    { id: "t2", name: "Aloha" },
    { id: "t3", name: "Danişment" },
    { id: "t4", name: "Denge Tekstil" },
    { id: "t5", name: "Elasteks" },
    { id: "t6", name: "Gapsan" },
    { id: "t7", name: "Garanti İplik" },
    { id: "t8", name: "Gülçağ" },
    { id: "t9", name: "İnfo İplik" },
    { id: "t10", name: "İstanbul İplik" },
  ],
  depolar: [
    { id: "MAIN", name: "Ana Depo" },
    { id: "AKS", name: "Aksesuar Depo" },
    { id: "AMBL", name: "Ambalaj Depo" },
  ],
  renkler: [
    { id: "r1", kod: "MRS 155", name: "Kırmızı" },
    { id: "r2", kod: "BLK 001", name: "Siyah" },
    { id: "r3", kod: "WHT 001", name: "Beyaz" },
    { id: "r4", kod: "NAV 042", name: "Lacivert" },
    { id: "r5", kod: "GRY 103", name: "Gri" },
    { id: "r6", kod: "CRM 205", name: "Krem" },
  ],
  aksesuarTipleri: [
    { id: "etiket", name: "Etiket" },
    { id: "aski", name: "Askı" },
    { id: "sticker", name: "Sticker" },
    { id: "koli", name: "Koli" },
    { id: "poset", name: "Poşet" },
    { id: "palet", name: "Palet" },
    { id: "kilcik", name: "Kılçık" },
    { id: "bant", name: "Bant" },
  ],
  aksesuarDetaylari: [
    { id: "e1", name: "Ahtapot", aksesuarTipiId: "etiket" },
    { id: "e2", name: "Normal Etiket", aksesuarTipiId: "etiket" },
    { id: "e3", name: "Kuşak", aksesuarTipiId: "etiket" },
    { id: "e4", name: "Zarf", aksesuarTipiId: "etiket" },
    { id: "e5", name: "Diğer Etiket", aksesuarTipiId: "etiket" },
    { id: "a1", name: "Askı", aksesuarTipiId: "aski" },
    { id: "s1", name: "Fiyat Stickeri", aksesuarTipiId: "sticker" },
    { id: "s2", name: "Barkod Stickeri", aksesuarTipiId: "sticker" },
    { id: "s3", name: "Karışım Stickeri", aksesuarTipiId: "sticker" },
    { id: "s4", name: "Genel Bilgi Stickeri", aksesuarTipiId: "sticker" },
    { id: "s5", name: "Poşet Üstü Stickeri", aksesuarTipiId: "sticker" },
    { id: "s6", name: "Koli Üstü Stickeri", aksesuarTipiId: "sticker" },
    { id: "k1", name: "İhracat Kolisi", aksesuarTipiId: "koli" },
    { id: "k2", name: "Taşıma Kolisi", aksesuarTipiId: "koli" },
    { id: "k3", name: "Numune Kolisi", aksesuarTipiId: "koli" },
    { id: "k4", name: "Diğer Koli", aksesuarTipiId: "koli" },
    { id: "p1", name: "İhracat Poşeti", aksesuarTipiId: "poset" },
    { id: "p2", name: "2. Kalite Poşeti", aksesuarTipiId: "poset" },
    { id: "p3", name: "Numune Poşeti", aksesuarTipiId: "poset" },
    { id: "p4", name: "Diğer Poşet", aksesuarTipiId: "poset" },
    { id: "pl1", name: "Euro Palet", aksesuarTipiId: "palet" },
    { id: "pl2", name: "Epal Palet", aksesuarTipiId: "palet" },
    { id: "pl3", name: "Genel Palet", aksesuarTipiId: "palet" },
    { id: "kl1", name: "Kılçık", aksesuarTipiId: "kilcik" },
    { id: "b1", name: "Şeffaf Bant", aksesuarTipiId: "bant" },
    { id: "b2", name: "Kahve Bant", aksesuarTipiId: "bant" },
    { id: "b3", name: "Sele Bant", aksesuarTipiId: "bant" },
  ],
  boyutlar: [
    { id: "ba1", name: "101 30*40", aksesuarTipiId: "aski" },
    { id: "ba2", name: "102 100*150", aksesuarTipiId: "aski" },
    { id: "ba3", name: "103 53*53", aksesuarTipiId: "aski" },
    { id: "ba4", name: "211 20*100", aksesuarTipiId: "aski" },
    { id: "ba5", name: "309 50*75", aksesuarTipiId: "aski" },
    { id: "bk1", name: "48*40*30", aksesuarTipiId: "koli" },
    { id: "bk2", name: "40*29*17", aksesuarTipiId: "koli" },
    { id: "bk3", name: "40*29*20", aksesuarTipiId: "koli" },
    { id: "bk4", name: "40*29*28", aksesuarTipiId: "koli" },
    { id: "bk5", name: "40*30*24", aksesuarTipiId: "koli" },
    { id: "bk6", name: "40*30*30", aksesuarTipiId: "koli" },
    { id: "bk7", name: "58*38*25", aksesuarTipiId: "koli" },
    { id: "bk8", name: "58*38*30", aksesuarTipiId: "koli" },
    { id: "bk9", name: "58*39*40", aksesuarTipiId: "koli" },
    { id: "bk10", name: "59*39*29", aksesuarTipiId: "koli" },
    { id: "bk11", name: "69,5*39*39", aksesuarTipiId: "koli" },
    { id: "bk12", name: "58*39*29", aksesuarTipiId: "koli" },
    { id: "bp1", name: "30*40+5", aksesuarTipiId: "poset" },
    { id: "bp2", name: "60*60+5", aksesuarTipiId: "poset" },
    { id: "bp3", name: "14,5*30+5", aksesuarTipiId: "poset" },
    { id: "bp4", name: "55+10+10*60", aksesuarTipiId: "poset" },
    { id: "bp5", name: "16*40+5", aksesuarTipiId: "poset" },
    { id: "bp6", name: "20*55+5", aksesuarTipiId: "poset" },
    { id: "bp7", name: "40*50+5", aksesuarTipiId: "poset" },
    { id: "bp8", name: "40*70+5", aksesuarTipiId: "poset" },
    { id: "bp9", name: "24*50+5", aksesuarTipiId: "poset" },
    { id: "bp10", name: "26*50+5", aksesuarTipiId: "poset" },
    { id: "bp11", name: "28*50+5", aksesuarTipiId: "poset" },
    { id: "bp12", name: "30*50+5", aksesuarTipiId: "poset" },
    { id: "bp13", name: "32*50+5", aksesuarTipiId: "poset" },
    { id: "bp14", name: "35*50+5", aksesuarTipiId: "poset" },
    { id: "bp15", name: "24*40+5", aksesuarTipiId: "poset" },
    { id: "bp16", name: "26*40+5", aksesuarTipiId: "poset" },
    { id: "bp17", name: "28*40+5", aksesuarTipiId: "poset" },
    { id: "bp18", name: "32*40+5", aksesuarTipiId: "poset" },
    { id: "bp19", name: "35*40+5", aksesuarTipiId: "poset" },
    { id: "bpl1", name: "80x120", aksesuarTipiId: "palet" },
    { id: "bpl2", name: "100x120", aksesuarTipiId: "palet" },
    { id: "bkl1", name: "5", aksesuarTipiId: "kilcik" },
    { id: "bkl2", name: "7", aksesuarTipiId: "kilcik" },
    { id: "bkl3", name: "11", aksesuarTipiId: "kilcik" },
    { id: "bkl4", name: "15", aksesuarTipiId: "kilcik" },
    { id: "bkl5", name: "17", aksesuarTipiId: "kilcik" },
    { id: "bkl6", name: "20", aksesuarTipiId: "kilcik" },
    { id: "bkl7", name: "25", aksesuarTipiId: "kilcik" },
    { id: "bkl8", name: "30", aksesuarTipiId: "kilcik" },
    { id: "bkl9", name: "35", aksesuarTipiId: "kilcik" },
    { id: "bkl10", name: "40", aksesuarTipiId: "kilcik" },
    { id: "bkl11", name: "50", aksesuarTipiId: "kilcik" },
    { id: "bb1", name: "45*100", aksesuarTipiId: "bant" },
    { id: "bb2", name: "75*100", aksesuarTipiId: "bant" },
    { id: "bb3", name: "15*66", aksesuarTipiId: "bant" },
  ],
};
